// ── Designer glyph ingestion ────────────────────────────────────────────────
// Drop designer SVGs into docs/badge-art/ named <badge-id>.svg (100x100
// viewBox, stroke-only paths per the asset spec), then run:
//   node scripts/ingestGlyphs.mjs
// Regenerates src/badges/glyphsArt.js. Art there overrides the placeholder
// glyphs in glyphs.js automatically.
import fs from 'fs'

const DIR = 'docs/badge-art'
const files = fs.existsSync(DIR) ? fs.readdirSync(DIR).filter(f => f.endsWith('.svg')) : []
const art = {}
const warnings = []

for (const f of files) {
  const id = f.replace('.svg', '')
  const svg = fs.readFileSync(`${DIR}/${f}`, 'utf8')
  const vb = svg.match(/viewBox="([\d.\s-]+)"/)?.[1]?.trim().split(/\s+/).map(Number)
  if (!vb || vb[2] !== 100 || vb[3] !== 100) warnings.push(`${f}: viewBox is not 0 0 100 100 — coords used as-is, check the render`)
  if (/<(text|image|rect|circle|ellipse|polygon|line)\b/.test(svg)) warnings.push(`${f}: contains non-path shapes — only <path> elements are ingested`)
  if (/fill="(?!none)[^"]/.test(svg)) warnings.push(`${f}: has filled paths — engraving expects stroke-only`)
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1])
  if (!ds.length) { warnings.push(`${f}: no <path d> found — SKIPPED`); continue }
  // width: median stroke-width if present, else spec default
  const sw = svg.match(/stroke-width="([\d.]+)"/)?.[1]
  art[id] = { d: ds.join(' '), abs: true, w: sw ? parseFloat(sw) : 6 }
}

const out = `// AUTO-GENERATED by scripts/ingestGlyphs.mjs from docs/badge-art/*.svg
// Designer art — overrides the placeholders in glyphs.js. Do not edit.
export const ART = ${JSON.stringify(art, null, 2)}
`
fs.writeFileSync('src/badges/glyphsArt.js', out)
console.log(`ingested ${Object.keys(art).length} designer glyph(s): ${Object.keys(art).join(', ') || '(none yet)'}`)
for (const w of warnings) console.log('⚠️ ', w)
