// ── Badge catalog ingestion ─────────────────────────────────────────────────
// Reads docs/badge-catalog-template.csv and regenerates:
//   src/badges/catalogData.js   (client catalog)
//   backend BADGE_CATALOG block (server mirror, between markers)
// Run: node scripts/ingestBadges.mjs
import fs from 'fs'

const csv = fs.readFileSync('docs/badge-catalog-template.csv', 'utf8').trim().split('\n')
const header = csv[0].split(',')
const rows = csv.slice(1).map(l => {
  const parts = l.split(',')
  const r = {}
  header.forEach((h, i) => r[h] = (parts[i] || '').trim())
  return r
})

// validate
const ids = new Set()
for (const r of rows) {
  if (!/^[a-z0-9]+$/.test(r.id)) throw new Error('bad id: ' + r.id)
  if (ids.has(r.id)) throw new Error('dup id: ' + r.id)
  ids.add(r.id)
  const lat = parseFloat(r.lat), lng = parseFloat(r.lng)
  if (!(lat > 40.45 && lat < 40.95 && lng > -74.3 && lng < -73.6)) throw new Error('coords outside NYC: ' + r.id)
  if (!['brass', 'nickel', 'copper', 'iris'].includes(r.finish)) throw new Error('bad finish: ' + r.id)
  if (r.season && !/^\d\d-\d\d~\d\d-\d\d$/.test(r.season)) throw new Error('bad season: ' + r.id)
  if (r.short_name.length > 15) throw new Error('short_name too long: ' + r.id)
}

// client catalog
const js = `// AUTO-GENERATED by scripts/ingestBadges.mjs from docs/badge-catalog-template.csv
// Do not edit by hand — edit the CSV and re-run the script.
export const CATALOG = ${JSON.stringify(rows.map(r => ({
  id: r.id, name: r.name, name_zh: r.name_zh || null, short: r.short_name,
  category: r.category, finish: r.finish, main: r.main === 'yes',
  lat: parseFloat(r.lat), lng: parseFloat(r.lng),
  season: r.season || null, radius: r.radius ? parseInt(r.radius) : null,
})), null, 2)}
`
fs.writeFileSync('src/badges/catalogData.js', js)

// server mirror
const py = rows.map(r =>
  `    "${r.id}": {"name": ${JSON.stringify(r.name)}, "lat": ${r.lat}, "lng": ${r.lng}` +
  `, "radius": ${r.radius || 200}${r.season ? `, "season": "${r.season}"` : ''}},`
).join('\n')
const block = `BADGE_CATALOG = {\n${py}\n}`
let share = fs.readFileSync('backend/share.py', 'utf8')
share = share.replace(/BADGE_CATALOG = \{[\s\S]*?\n\}/, block)
fs.writeFileSync('backend/share.py', share)
console.log(`ingested ${rows.length} badges (${rows.filter(r => r.finish === 'brass').length} brass, ${rows.filter(r => r.finish === 'nickel').length} nickel, ${rows.filter(r => r.finish === 'copper').length} copper, ${rows.filter(r => r.finish === 'iris').length} iris)`)
